### ISSUE TITLE
npm repository url is incorrect

### ISSUE THREAD

**Issue by ssbarnea** [nteract/ansi-to-react#32]
Package published at https://www.npmjs.com/package/ansi-to-react points to https://github.com/nteract/nteract/tree/master/packages/ansi-to-react instead of the current repository.

**Comment by captainsafia** [comment]
Fixed. Thanks for reporting!

**Comment by ssbarnea** [comment]
@captainsafia The problem was still not fixed, the right side panel from NPM still indicates the wrong url for this package, giving a 404.

https://github.com/nteract/nteract/tree/master/packages/ansi-to-react

The only link that is correct is the issue tracker link from the bottom.

**Comment by captainsafia** [comment]
The issue is fixed in the `package.json` file but won't show up on NPM until a publish was done.

I wanted to avoid publishing a new patch version with no code changes and was waiting to publish until we had a bug fix or something come in.

Since that likely won't happen for a bit, I've publish a patch release just now.
